<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="IN2374582W1" name="com.qa.executiontestcases.MUAccessExecutionForSingleUserSingleAccess" tests="3" failures="0" timestamp="14 Nov 2019 15:28:55 GMT" time="0.095" errors="1">
  <testcase name="singleUserSingleAccessExecution" time="0.095" classname="com.qa.executiontestcases.MUAccessExecutionForSingleUserSingleAccess">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.qa.executiontestcases.MUAccessExecutionForSingleUserSingleAccess.getApprovalLevel(MUAccessExecutionForSingleUserSingleAccess.java:144)
at com.qa.executiontestcases.MUAccessExecutionForSingleUserSingleAccess.singleUserSingleAccessExecution(MUAccessExecutionForSingleUserSingleAccess.java:152)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- singleUserSingleAccessExecution -->
  <testcase name="singleUserSingleAccessAutoApprovedExecution" classname="com.qa.executiontestcases.MUAccessExecutionForSingleUserSingleAccess">
    <skipped/>
  </testcase> <!-- singleUserSingleAccessAutoApprovedExecution -->
  <testcase name="singleUserMultipleAccessExecution" classname="com.qa.executiontestcases.MUAccessExecutionForSingleUserSingleAccess">
    <skipped/>
  </testcase> <!-- singleUserMultipleAccessExecution -->
</testsuite> <!-- com.qa.executiontestcases.MUAccessExecutionForSingleUserSingleAccess -->
